package yuksi.GUI.UyeIslemleri;

import VeriErisimSiniflari.Baglan;
import VeriErisimSiniflari.Guncelle;
import VeriErisimSiniflari.VerileriGoster;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class UyedeOlanKitaplar extends javax.swing.JPanel {

    JFrame frame;
    Connection con;
    VerileriGoster vg;
    DefaultTableModel modelTable;
    String id;
    Baglan b;

    public UyedeOlanKitaplar(JFrame frame, String id) {
        initComponents();

        this.frame = frame;
        frame.setContentPane(this);
        frame.setSize(652, 600);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.setVisible(true);
        System.out.println("UOKId" + id);
        try {
            con = DriverManager.getConnection("jdbc:sqlserver://127.0.0.1:1433;database=Kutuphane;user=root;password=1234");
        } catch (SQLException ex) {
            System.out.println("Bağlantı Hatası");
        }
        this.id = id;
        System.out.println("UOKId2" + id);
        String sorgu = "SELECT kitapId,kitapAd,yazar,alisTarihi,teslimTarihi,kitapOnay,ceza FROM Kitaplik"
                + " where kitapIstekId=" + id;

        String guncelleSorgu = "update Kitaplik set ceza = (0.25*datediff(day,teslimTarihi,getdate())) "
                + "where((0.25*datediff(day,teslimTarihi,getdate())) > 0) "
                + "and kitapSahibiId=" + id + " and kitapOnay='Onaylandı'";

        vg = new VerileriGoster(con, sorgu);
        modelTable = vg.getTable((DefaultTableModel) jTable1.getModel());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BtnAnasayfa = new javax.swing.JButton();
        BtnKitapAl = new javax.swing.JButton();
        BtnOlanKitaplar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnCeza = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnIade = new javax.swing.JButton();

        setLayout(null);

        BtnAnasayfa.setText("Anasayfa");
        BtnAnasayfa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAnasayfaActionPerformed(evt);
            }
        });
        add(BtnAnasayfa);
        BtnAnasayfa.setBounds(70, 90, 100, 23);

        BtnKitapAl.setText("Kitap Al");
        BtnKitapAl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnKitapAlActionPerformed(evt);
            }
        });
        add(BtnKitapAl);
        BtnKitapAl.setBounds(240, 90, 100, 23);

        BtnOlanKitaplar.setText("Bende Olan Kitaplar");
        BtnOlanKitaplar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnOlanKitaplarActionPerformed(evt);
            }
        });
        add(BtnOlanKitaplar);
        BtnOlanKitaplar.setBounds(400, 90, 170, 23);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Kitap Id", "Kitap Adı", "Yazar", "Alış Tarihi", "Teslim Tarihi", "Durum", "Ceza"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1);
        jScrollPane1.setBounds(10, 130, 590, 360);

        btnCeza.setText("Ceza Öde");
        btnCeza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCezaActionPerformed(evt);
            }
        });
        add(btnCeza);
        btnCeza.setBounds(350, 510, 100, 23);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(139, 69, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("KÜTÜPHANE TAKİP SİSTEMİ");
        add(jLabel1);
        jLabel1.setBounds(10, 20, 600, 50);

        btnIade.setText("İade Et");
        btnIade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIadeActionPerformed(evt);
            }
        });
        add(btnIade);
        btnIade.setBounds(200, 510, 100, 23);
    }// </editor-fold>//GEN-END:initComponents

    private void BtnAnasayfaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAnasayfaActionPerformed
        UyeGirisAnasayfa uga = new UyeGirisAnasayfa(frame, id);
    }//GEN-LAST:event_BtnAnasayfaActionPerformed

    private void BtnKitapAlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnKitapAlActionPerformed
        UyeKitapAl uka = new UyeKitapAl(frame, id);
    }//GEN-LAST:event_BtnKitapAlActionPerformed

    private void BtnOlanKitaplarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnOlanKitaplarActionPerformed
        UyedeOlanKitaplar uka = new UyedeOlanKitaplar(frame, id);
    }//GEN-LAST:event_BtnOlanKitaplarActionPerformed

    private float getCeza(String kitapId) {
        float x = 0;
        try {
            Statement stmt = con.createStatement();
            ResultSet rs = stmt.executeQuery("select ceza from Kitaplik "
                    + "where kitapId='" + kitapId + "'");
            rs.next();
            x = rs.getFloat(1);
        } catch (SQLException ex) {
            //System.out.println("Ceza Hatası");
        }
        return x;
    }

    private int getKitapCount() {
        int x = 0;
        try {
            Statement stmt = con.createStatement();
            ResultSet rs = stmt.executeQuery("select kitapCount from Kullanici where id='"
                    + id + "'");
            rs.next();
            x = rs.getInt(1);
        } catch (SQLException ex) {
            System.out.println("Count hata oluştu");
        }
        System.out.println(x);
        return --x;
    }
    private void btnCezaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCezaActionPerformed
        //String cezaSorgu = "select ceza from Kitaplik where kitapSahibiId='"+id+"'";
        String sorgu = "update Kitaplik set ceza = 0";
        JOptionPane.showMessageDialog(this, "Basarıyla Ödendi");
    }//GEN-LAST:event_btnCezaActionPerformed

    private void btnIadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIadeActionPerformed
        if (jTable1.getSelectedRow() != -1) {
            if (getCeza(modelTable.getValueAt(jTable1.getSelectedRow(), 0).toString()) >= 0) {
                String sorgu = "update Kitaplik set kitapOnay='Alınabilir' where kitapId="
                        + modelTable.getValueAt(jTable1.getSelectedRow(), 0);
                sorgu += "update Kitaplik set kitapIstekId=0 where kitapId="
                        + modelTable.getValueAt(jTable1.getSelectedRow(), 0);
                sorgu += "update Kullanici set kitapCount=" + (getKitapCount())
                        + " where id=" + id;
                sorgu += "update Kitaplik set alisTarihi=NULL where kitapId="
                        + modelTable.getValueAt(jTable1.getSelectedRow(), 0);
                sorgu += "update Kitaplik set teslimTarihi=NULL where kitapId="
                        + modelTable.getValueAt(jTable1.getSelectedRow(), 0);
                Guncelle g = new Guncelle(con, sorgu);
                for (int i = modelTable.getRowCount() - 1; i >= 0; i--) {
                    modelTable.removeRow(i);
                }
                modelTable = vg.getTable((DefaultTableModel) jTable1.getModel());
            }

        }

    }//GEN-LAST:event_btnIadeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAnasayfa;
    private javax.swing.JButton BtnKitapAl;
    private javax.swing.JButton BtnOlanKitaplar;
    private javax.swing.JButton btnCeza;
    private javax.swing.JButton btnIade;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
