package yuksi.GUI.UyeIslemleri;

import yuksi.Giris;
import VeriErisimSiniflari.Baglan;
import VeriErisimSiniflari.VerileriGoster;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;

import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;
import yuksi.GUI.AdminIslemleri.AdminDuyuruEkle;
import yuksi.GUI.AdminIslemleri.DuyuruIcerik;

/**
 *
 * @author yukse
 */
public class UyeGirisAnasayfa extends javax.swing.JPanel {

    String id;
    Connection con;
    JFrame frame;
    VerileriGoster vg;
    public DefaultTableModel modelTable;
    AdminDuyuruEkle ade;
    public static int duyuruId2;
    Baglan b;

    public UyeGirisAnasayfa(JFrame frame, String id) {
        initComponents();
        String ad = "";
        String soyad = "";
        this.frame = frame;
        frame.setContentPane(this);
        frame.setSize(1300, 600);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.setVisible(true);
        this.id = id;

        try {
            con = DriverManager.getConnection("jdbc:sqlserver://127.0.0.1:1433;database=Kutuphane;user=root;password=1234");
            Statement stmt = con.createStatement();
            ResultSet rs = stmt.executeQuery("select ad,soyad from Kullanici where id=" + id);
            rs.next();
            ad = rs.getString(1);
            soyad = rs.getString(2);

        } catch (SQLException ex) {
            System.out.println("hata");
        }
        lblAd.setText(ad);
        lblSoyad.setText(soyad);

        String sorgu = " select baslik,tarih,ileten from Duyurular";
        vg = new VerileriGoster(con, sorgu);
        modelTable = vg.getTable((DefaultTableModel) jTable1.getModel());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BtnOlanKitap = new javax.swing.JButton();
        BtnAnaSayfa = new javax.swing.JButton();
        BtnKitapAl = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lblSoyad = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnCikis = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        lblAd = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setLayout(null);

        BtnOlanKitap.setText("Bende Olan Kitaplar");
        BtnOlanKitap.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BtnOlanKitap.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        BtnOlanKitap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnOlanKitapActionPerformed(evt);
            }
        });
        add(BtnOlanKitap);
        BtnOlanKitap.setBounds(190, 80, 150, 22);

        BtnAnaSayfa.setText("Anasayfa");
        BtnAnaSayfa.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BtnAnaSayfa.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        BtnAnaSayfa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAnaSayfaActionPerformed(evt);
            }
        });
        add(BtnAnaSayfa);
        BtnAnaSayfa.setBounds(10, 80, 90, 22);

        BtnKitapAl.setText("Kitap Al");
        BtnKitapAl.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BtnKitapAl.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        BtnKitapAl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnKitapAlActionPerformed(evt);
            }
        });
        add(BtnKitapAl);
        BtnKitapAl.setBounds(100, 80, 80, 22);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);
        jPanel1.add(lblSoyad);
        lblSoyad.setBounds(130, 60, 180, 30);

        jLabel2.setText("Soyadı : ");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(30, 60, 50, 30);

        btnCikis.setText("Çıkış");
        btnCikis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCikisActionPerformed(evt);
            }
        });
        jPanel1.add(btnCikis);
        btnCikis.setBounds(370, 110, 70, 23);

        jLabel4.setText("Adı : ");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(30, 20, 50, 30);
        jPanel1.add(lblAd);
        lblAd.setBounds(130, 20, 200, 30);

        add(jPanel1);
        jPanel1.setBounds(10, 120, 460, 140);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(null);

        jLabel3.setText("Duyurular");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(30, 20, 81, 30);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Başlık", "Tarih", "İleten"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(30, 60, 1100, 170);

        add(jPanel2);
        jPanel2.setBounds(30, 270, 1140, 260);
    }// </editor-fold>//GEN-END:initComponents

    private void BtnOlanKitapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnOlanKitapActionPerformed
        UyedeOlanKitaplar uka = new UyedeOlanKitaplar(frame, id);
    }//GEN-LAST:event_BtnOlanKitapActionPerformed

    private void btnCikisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCikisActionPerformed
        Giris ge = new Giris(frame);
    }//GEN-LAST:event_btnCikisActionPerformed

    private void BtnAnaSayfaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAnaSayfaActionPerformed

    }//GEN-LAST:event_BtnAnaSayfaActionPerformed

    private void BtnKitapAlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnKitapAlActionPerformed
        UyeKitapAl uka = new UyeKitapAl(frame, id);
    }//GEN-LAST:event_BtnKitapAlActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        if (jTable1.getSelectedColumn() == 0) {
            duyuruId2 = getDuyurId();
            DuyuruIcerik di = new DuyuruIcerik(frame, id);
        }
    }//GEN-LAST:event_jTable1MouseClicked
    private int getDuyurId() {
        System.out.println("row" + modelTable.getValueAt(jTable1.getSelectedRow(), 0));
        int x = 0;
        try {
            Statement stmt = con.createStatement();
            ResultSet rs = stmt.executeQuery("Select duyuruId from Duyurular "
                    + " where baslik='" + modelTable.getValueAt(jTable1.getSelectedRow(), 0) + "'");
            rs.next();
            x = rs.getInt(1);
        } catch (SQLException ex) {
            System.out.println("DuyurId hata oluştu");
        }
        return x;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAnaSayfa;
    private javax.swing.JButton BtnKitapAl;
    private javax.swing.JButton BtnOlanKitap;
    private javax.swing.JButton btnCikis;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblAd;
    private javax.swing.JLabel lblSoyad;
    // End of variables declaration//GEN-END:variables
}
