package yuksi.GUI.UyeIslemleri;

import yuksi.Giris;
import VeriErisimSiniflari.Baglan;
import VeriErisimSiniflari.Ekle;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

public class UyeKayit extends javax.swing.JPanel {

    JFrame frame;
    Connection con;
    Baglan b;

    public UyeKayit(JFrame frame) {
        initComponents();

        this.frame = frame;
        frame.setContentPane(this);
        frame.setSize(652, 530);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.setVisible(true);
        try {
            con = DriverManager.getConnection("jdbc:sqlserver://127.0.0.1:1433;database=Kutuphane;user=root;password=1234");
        } catch (SQLException ex) {
            System.out.println("Bağlantı Hatası");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        boxAd = new javax.swing.JTextField();
        boxSoyad = new javax.swing.JTextField();
        btnUye = new javax.swing.JButton();
        btnGiris = new javax.swing.JButton();
        boxSifre = new javax.swing.JPasswordField();
        boxSifre2 = new javax.swing.JPasswordField();
        boxKad = new javax.swing.JTextField();
        comboYetki = new javax.swing.JComboBox<>();

        setMaximumSize(new java.awt.Dimension(620, 500));
        setMinimumSize(new java.awt.Dimension(620, 500));
        setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(139, 69, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("KÜTÜPHANE TAKİP SİSTEMİ");
        add(jLabel1);
        jLabel1.setBounds(10, 60, 600, 50);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(139, 69, 0));
        jLabel2.setText("Yetki : ");
        add(jLabel2);
        jLabel2.setBounds(90, 380, 150, 22);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(139, 69, 0));
        jLabel3.setText("Adınız : ");
        add(jLabel3);
        jLabel3.setBounds(90, 150, 150, 22);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(139, 69, 0));
        jLabel4.setText("Soyadınız : ");
        add(jLabel4);
        jLabel4.setBounds(90, 190, 150, 22);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(139, 69, 0));
        jLabel5.setText("Kullanıcı Adınız : ");
        add(jLabel5);
        jLabel5.setBounds(90, 230, 150, 22);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(139, 69, 0));
        jLabel6.setText("Şifreniz : ");
        add(jLabel6);
        jLabel6.setBounds(90, 280, 150, 22);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(139, 69, 0));
        jLabel7.setText("Şifre Tekrar : ");
        add(jLabel7);
        jLabel7.setBounds(90, 330, 150, 22);
        add(boxAd);
        boxAd.setBounds(320, 150, 150, 22);
        add(boxSoyad);
        boxSoyad.setBounds(320, 190, 150, 22);

        btnUye.setText("Üye Ol");
        btnUye.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUyeActionPerformed(evt);
            }
        });
        add(btnUye);
        btnUye.setBounds(320, 410, 100, 23);

        btnGiris.setText("Giriş");
        btnGiris.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGirisActionPerformed(evt);
            }
        });
        add(btnGiris);
        btnGiris.setBounds(475, 453, 120, 20);
        add(boxSifre);
        boxSifre.setBounds(320, 280, 150, 22);
        add(boxSifre2);
        boxSifre2.setBounds(320, 320, 150, 22);

        boxKad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxKadActionPerformed(evt);
            }
        });
        add(boxKad);
        boxKad.setBounds(320, 230, 150, 22);

        comboYetki.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Öğrenci", "Öğretmen" }));
        comboYetki.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboYetkiActionPerformed(evt);
            }
        });
        add(comboYetki);
        comboYetki.setBounds(320, 370, 150, 20);
    }// </editor-fold>//GEN-END:initComponents
     private int getId() {
        int x = 0;
        try {
            Statement stmt = con.createStatement();
            ResultSet rs = stmt.executeQuery("Select max(id) from Kullanici");
            rs.next();
            x = rs.getInt(1);
        } catch (SQLException ex) {
            //System.out.println("ID  hata oluştu");
        }
        return x;
    }

    private boolean isNickTaken(String nick) {
        try {
            Statement stmt = con.createStatement();
            ResultSet rs = stmt.executeQuery("SELECT kullaniciAdi from Kullanici "
                    + " where kullaniciAdi='" + nick + "'");
            rs.next();
            rs.getString(1);
            return false;
        } catch (SQLException ex) {
            //System.out.println("ID Hatası olustu");
            return true;
        }
    }
    private void btnUyeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUyeActionPerformed
        if (!boxAd.getText().equals("") && !boxSoyad.getText().equals("")
                && !boxKad.getText().equals("") && !boxSifre.getText().equals("")
                && !boxSifre2.getText().equals("")) {
            if (boxSifre.getText().equals(boxSifre2.getText())) {
                if (isNickTaken(boxKad.getText())) {
                    String sorgu = "INSERT INTO Kullanici (id,ad,soyad,kullaniciAdi,sifre,yetki) "
                            + " VALUES ('" + (getId() + 1) + "','" + boxAd.getText() + "','" + boxSoyad.getText()
                            + "','" + boxKad.getText() + "','" + boxSifre.getText() + "','" + comboYetki.getSelectedItem() + "')";
                    Ekle e = new Ekle(con, sorgu);
                    JOptionPane.showMessageDialog(this, "Başarıyla Eklendi");
                    boxAd.setText("");
                    boxSoyad.setText("");
                    boxKad.setText("");
                    boxSifre.setText("");
                    boxSifre2.setText("");
                    comboYetki.setSelectedIndex(0);
                } else {
                    JOptionPane.showMessageDialog(this, "Farklı Kullanici Adı Deneyin!");
                }
            } else {
                JOptionPane.showMessageDialog(this, "Şifreler Uyusmuyor");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Bütün Alanları Doldurun");
        }

    }//GEN-LAST:event_btnUyeActionPerformed

    private void btnGirisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGirisActionPerformed
        Giris ge = new Giris(frame);
    }//GEN-LAST:event_btnGirisActionPerformed

    private void boxKadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxKadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boxKadActionPerformed

    private void comboYetkiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboYetkiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboYetkiActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField boxAd;
    private javax.swing.JTextField boxKad;
    private javax.swing.JPasswordField boxSifre;
    private javax.swing.JPasswordField boxSifre2;
    private javax.swing.JTextField boxSoyad;
    private javax.swing.JButton btnGiris;
    private javax.swing.JButton btnUye;
    private javax.swing.JComboBox<String> comboYetki;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables
}
