package yuksi.GUI.UyeIslemleri;

import VeriErisimSiniflari.Baglan;
import VeriErisimSiniflari.Guncelle;
import VeriErisimSiniflari.VerileriGoster;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class UyeKitapAl extends javax.swing.JPanel {

    JFrame frame;
    Connection con;
    VerileriGoster vg;
    DefaultTableModel modelTable;
    String id;
    Baglan b;

    public UyeKitapAl(JFrame frame, String id) {
        initComponents();

        this.frame = frame;
        frame.setContentPane(this);
        frame.setSize(652, 540);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.setVisible(true);
        try {
            con = DriverManager.getConnection("jdbc:sqlserver://127.0.0.1:1433;database=Kutuphane;user=root;password=1234");
        } catch (SQLException ex) {
            System.out.println("Bağlantı Hatası");
        }
        this.id = id;
        System.out.println("ukaID" + id);
        String sorgu = "SELECT kitapId,kitapAd,kitapTur,yazar,yayinEvi,kitapOnay,yerNo FROM Kitaplik";
        vg = new VerileriGoster(con, sorgu);
        modelTable = vg.getTable((DefaultTableModel) jTable1.getModel());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BtnBendeOlanKitaplar = new javax.swing.JButton();
        BtnAnasayfa = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        BtnKitapAl = new javax.swing.JButton();
        boxAra = new javax.swing.JTextField();
        btnAra = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTextField2 = new javax.swing.JTextField();
        boxKitapAl = new javax.swing.JButton();

        setLayout(null);

        BtnBendeOlanKitaplar.setText("Bende Olan Kitaplar");
        BtnBendeOlanKitaplar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BtnBendeOlanKitaplar.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        BtnBendeOlanKitaplar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBendeOlanKitaplarActionPerformed(evt);
            }
        });
        add(BtnBendeOlanKitaplar);
        BtnBendeOlanKitaplar.setBounds(240, 24, 150, 22);

        BtnAnasayfa.setText("Anasayfa");
        BtnAnasayfa.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BtnAnasayfa.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        BtnAnasayfa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAnasayfaActionPerformed(evt);
            }
        });
        add(BtnAnasayfa);
        BtnAnasayfa.setBounds(38, 24, 100, 22);

        jButton3.setText("jButton1");
        jButton3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        add(jButton3);
        jButton3.setBounds(38, 24, 100, 22);

        BtnKitapAl.setText("Kitap Al");
        BtnKitapAl.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BtnKitapAl.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        BtnKitapAl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnKitapAlActionPerformed(evt);
            }
        });
        add(BtnKitapAl);
        BtnKitapAl.setBounds(140, 24, 100, 22);
        add(boxAra);
        boxAra.setBounds(170, 70, 200, 25);

        btnAra.setText("ARA");
        btnAra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAraActionPerformed(evt);
            }
        });
        add(btnAra);
        btnAra.setBounds(400, 70, 70, 23);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Kitap Id", "Kitap Adı", "Kitap Türü", "Yazar", "Yayin Evi", "Durum", "Yer Numarası"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1);
        jScrollPane1.setBounds(10, 100, 570, 270);
        add(jTextField2);
        jTextField2.setBounds(10, 380, 570, 80);

        boxKitapAl.setText("Kitap Al");
        boxKitapAl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxKitapAlActionPerformed(evt);
            }
        });
        add(boxKitapAl);
        boxKitapAl.setBounds(260, 470, 90, 23);
    }// </editor-fold>//GEN-END:initComponents

    private void BtnKitapAlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnKitapAlActionPerformed
        UyeKitapAl uka = new UyeKitapAl(frame, id);
    }//GEN-LAST:event_BtnKitapAlActionPerformed

    private void BtnBendeOlanKitaplarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBendeOlanKitaplarActionPerformed
        UyedeOlanKitaplar uka = new UyedeOlanKitaplar(frame, id);
    }//GEN-LAST:event_BtnBendeOlanKitaplarActionPerformed

    private void btnAraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAraActionPerformed
        String sorgu = "SELECT (kitapId,kitapAd,kitapTur,yazar,yayinEvi,yerNo) FROM Kitaplik "
                + "WHERE kitapAd='" + boxAra.getText() + "'";
        int konum = getArananRow(boxAra.getText());
        jTable1.setRowSelectionInterval(konum, konum);
        jTable1.scrollRectToVisible(jTable1.getCellRect(konum, 0, true));

    }//GEN-LAST:event_btnAraActionPerformed
    public String getYetki() {
        try {
            Statement stmt = con.createStatement();
            ResultSet rs = stmt.executeQuery("select yetki from Kullanici"
                    + " where id='" + id + "'");
            rs.next();
            return rs.getString(1);
        } catch (SQLException ex) {
            System.out.println("getYetki hata oluştu");
        }
        return "";
    }

    private String getOnay(String kitapId) {
        String onay = null;
        try {
            Statement stmt = con.createStatement();
            ResultSet rs = stmt.executeQuery("select kitapOnay from Kitaplik"
                    + " where kitapId='" + kitapId + "'");
            rs.next();
            onay = rs.getString(1);
        } catch (SQLException ex) {
            System.out.println("getOnay hata oluştu");
        }
        if (onay == null) {
            return "";
        }
        return onay;
    }

    private int getKitapCount() {
        int x = 0;
        try {
            Statement stmt = con.createStatement();
            ResultSet rs = stmt.executeQuery("select kitapCount from Kullanici where id='"
                    + id + "'");
            rs.next();
            x = rs.getInt(1);
        } catch (SQLException ex) {
            System.out.println("Count hata oluştu");
        }
        System.out.println(x);
        return x;
    }

    private int getArananRow(String aranan) {
        for (int i = 0; i < jTable1.getRowCount(); i++) {
            if (jTable1.getModel().getValueAt(i, 1).equals(aranan)) {
                return i;
            }
        }
        return 0;
    }

    private void boxKitapAlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxKitapAlActionPerformed
        if (jTable1.getSelectedRow() != -1) {
            String onayDurumu = modelTable.getValueAt(jTable1.getSelectedRow(), 0).toString();
            if (!getOnay(onayDurumu).equals("İstendi") && !getOnay(onayDurumu).equals("Onaylandı")) {
                int sayi;
                if (getYetki().equals("Öğrenci")) {
                    sayi = 3;
                } else {
                    sayi = 5;
                }
                if (getKitapCount() < 3) {
                    String sorgu = "update Kitaplik set kitapIstekId='" + id + "'"
                            + " where kitapId='"
                            + modelTable.getValueAt(jTable1.getSelectedRow(), 0) + "'";
                    sorgu += "update Kullanici set KitapCount='" + (getKitapCount() + 1) + "'"
                            + " where id='" + id + "'";
                    sorgu += "update Kitaplik set kitapOnay='İstendi' "
                            + " where kitapId='"
                            + modelTable.getValueAt(jTable1.getSelectedRow(), 0) + "'";
                    Guncelle g = new Guncelle(con, sorgu);
                    for (int i = modelTable.getRowCount() - 1; i >= 0; i--) {
                        modelTable.removeRow(i);
                    }
                    modelTable = vg.getTable((DefaultTableModel) jTable1.getModel());
                } else {
                    JOptionPane.showMessageDialog(this, "Daha fazla Kitap İsteyemessiniz");
                }
            } else {
                JOptionPane.showMessageDialog(this, "Bu Kitap zaten İstendi");
            }
        }
    }//GEN-LAST:event_boxKitapAlActionPerformed

    private void BtnAnasayfaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAnasayfaActionPerformed
        UyeGirisAnasayfa uga = new UyeGirisAnasayfa(frame, id);
    }//GEN-LAST:event_BtnAnasayfaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAnasayfa;
    private javax.swing.JButton BtnBendeOlanKitaplar;
    private javax.swing.JButton BtnKitapAl;
    private javax.swing.JTextField boxAra;
    private javax.swing.JButton boxKitapAl;
    private javax.swing.JButton btnAra;
    private javax.swing.JButton jButton3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
