package yuksi.GUI.AdminIslemleri;

import yuksi.Giris;
import VeriErisimSiniflari.Baglan;
import static VeriErisimSiniflari.SQL_Server_Connection.con;
import VeriErisimSiniflari.Sil;
import VeriErisimSiniflari.VerileriGoster;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import static javafx.application.Platform.exit;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;

public class AdminUyeIslem extends javax.swing.JPanel {

    JFrame frame;
    String id;
    VerileriGoster vg;
    Baglan b;
    DefaultTableModel model;

    public AdminUyeIslem(JFrame frame) {
        initComponents();
        this.frame = frame;
        frame.setContentPane(this);
        frame.setSize(850, 560);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.setVisible(true);
        try {
            con = DriverManager.getConnection("jdbc:sqlserver://127.0.0.1:1433;database=Kutuphane;user=root;password=1234");
        } catch (SQLException ex) {
            System.out.println("Bağlantı Hatası");
        }
        this.id = id;
        String sorgu = "SELECT id,ad,soyad,kullaniciAdi,sifre,yetki FROM Kullanici";
        vg = new VerileriGoster(con, sorgu);
        model = vg.getTable((DefaultTableModel) jTable1.getModel());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnDuyuru = new javax.swing.JButton();
        btnUyeIslem = new javax.swing.JButton();
        btnKitapIslem = new javax.swing.JButton();
        btnKitapOnay = new javax.swing.JButton();
        btnYetkili = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        boxAra = new javax.swing.JTextField();
        btnAra = new javax.swing.JButton();
        btnCikar = new javax.swing.JButton();
        btnCikis = new javax.swing.JButton();

        setLayout(null);

        btnDuyuru.setText("Duyuru Ekle");
        btnDuyuru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDuyuruActionPerformed(evt);
            }
        });
        add(btnDuyuru);
        btnDuyuru.setBounds(310, 50, 110, 22);

        btnUyeIslem.setText("Üye İşlem");
        btnUyeIslem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUyeIslemActionPerformed(evt);
            }
        });
        add(btnUyeIslem);
        btnUyeIslem.setBounds(10, 50, 100, 22);

        btnKitapIslem.setText("Kitap İşlem");
        btnKitapIslem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKitapIslemActionPerformed(evt);
            }
        });
        add(btnKitapIslem);
        btnKitapIslem.setBounds(110, 50, 100, 22);

        btnKitapOnay.setText("Kitap Onay");
        btnKitapOnay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKitapOnayActionPerformed(evt);
            }
        });
        add(btnKitapOnay);
        btnKitapOnay.setBounds(210, 50, 100, 22);

        btnYetkili.setText("Yetkili Ekle");
        btnYetkili.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnYetkiliActionPerformed(evt);
            }
        });
        add(btnYetkili);
        btnYetkili.setBounds(420, 50, 100, 22);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "Adı", "Soyadı", "Kullanıcı Adı", "Şifresi", "Yetkisi"
            }
        ));
        jTable1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1);
        jScrollPane1.setBounds(12, 190, 820, 290);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("Adı");

        boxAra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxAraActionPerformed(evt);
            }
        });

        btnAra.setText("ARA");
        btnAra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(172, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(boxAra, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80)
                .addComponent(btnAra, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(158, 158, 158))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boxAra, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAra))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        add(jPanel1);
        jPanel1.setBounds(10, 80, 830, 100);

        btnCikar.setText("Çıkar");
        btnCikar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCikarActionPerformed(evt);
            }
        });
        add(btnCikar);
        btnCikar.setBounds(350, 490, 100, 23);

        btnCikis.setText("Çıkış");
        btnCikis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCikisActionPerformed(evt);
            }
        });
        add(btnCikis);
        btnCikis.setBounds(730, 10, 100, 23);
    }// </editor-fold>//GEN-END:initComponents

    private void boxAraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxAraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boxAraActionPerformed

    private void btnUyeIslemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUyeIslemActionPerformed

    }//GEN-LAST:event_btnUyeIslemActionPerformed

    private void btnKitapIslemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKitapIslemActionPerformed
        AdminKitapIslem aki = new AdminKitapIslem(frame);
    }//GEN-LAST:event_btnKitapIslemActionPerformed

    private void btnKitapOnayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKitapOnayActionPerformed
        AdminKitapOnay ako = new AdminKitapOnay(frame);
    }//GEN-LAST:event_btnKitapOnayActionPerformed

    private void btnDuyuruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDuyuruActionPerformed
        AdminDuyuruEkle ade = new AdminDuyuruEkle(frame, id);
    }//GEN-LAST:event_btnDuyuruActionPerformed

    private void btnYetkiliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnYetkiliActionPerformed
        AdminYetkiliEkle aye = new AdminYetkiliEkle(frame);
    }//GEN-LAST:event_btnYetkiliActionPerformed

    private void btnAraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAraActionPerformed

        String sorgu = "SELECT id,ad,soyad,kullaniciAdi,sifre,yetki FROM Kullanici "
                + "WHERE kullaniciAdi='" + boxAra.getText() + "'";
        int konum = getArananRow(boxAra.getText());
        jTable1.setRowSelectionInterval(konum, konum);
        jTable1.scrollRectToVisible(jTable1.getCellRect(konum, 0, true));


    }//GEN-LAST:event_btnAraActionPerformed
    private int getArananRow(String aranan) {
        for (int i = 0; i < jTable1.getRowCount(); i++) {
            if (jTable1.getModel().getValueAt(i, 3).equals(aranan)) {
                return i;
            }
        }
        return 0;
    }

    private void btnCikisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCikisActionPerformed
        Giris GE = new Giris(frame);
    }//GEN-LAST:event_btnCikisActionPerformed

    Sil sil;
    private void btnCikarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCikarActionPerformed
        String sorgu = "DELETE  Kullanici WHERE kullaniciAdi='"
                + model.getValueAt(jTable1.getSelectedRow(), 3) + "'";
        sil = new Sil(con, sorgu);
        for (int i = model.getRowCount() - 1; i >= 0; i--) {
            model.removeRow(i);
        }
        model = vg.getTable((DefaultTableModel) jTable1.getModel());
    }//GEN-LAST:event_btnCikarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField boxAra;
    private javax.swing.JButton btnAra;
    private javax.swing.JButton btnCikar;
    private javax.swing.JButton btnCikis;
    private javax.swing.JButton btnDuyuru;
    private javax.swing.JButton btnKitapIslem;
    private javax.swing.JButton btnKitapOnay;
    private javax.swing.JButton btnUyeIslem;
    private javax.swing.JButton btnYetkili;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
