package yuksi.GUI.AdminIslemleri;

import VeriErisimSiniflari.Baglan;
import VeriErisimSiniflari.Ekle;
import static VeriErisimSiniflari.SQL_Server_Connection.con;
import VeriErisimSiniflari.VerileriGoster;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class AdminYetkiliEkle extends javax.swing.JPanel {

    JFrame frame;
    Connection con;
    Baglan b;

    public AdminYetkiliEkle(JFrame frame) {
        initComponents();
        this.frame = frame;
        frame.setContentPane(this);
        frame.setSize(650, 520);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.setVisible(true);
        try {
            con = DriverManager.getConnection("jdbc:sqlserver://127.0.0.1:1433;database=Kutuphane;user=root;password=1234");
        } catch (SQLException ex) {
            System.out.println("Bağlantı Hatası");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        btnCikis = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        boxAd = new javax.swing.JTextField();
        boxSoyad = new javax.swing.JTextField();
        boxKad = new javax.swing.JTextField();
        comboYetki = new javax.swing.JComboBox<>();
        btnYetki = new javax.swing.JButton();
        boxSifre2 = new javax.swing.JPasswordField();
        boxSifre = new javax.swing.JPasswordField();

        setLayout(null);

        jButton1.setText("Duyuru Ekle");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1);
        jButton1.setBounds(310, 90, 110, 22);

        jButton2.setText("Üye İşlem");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2);
        jButton2.setBounds(10, 90, 100, 22);

        jButton3.setText("Kitap İşlem");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        add(jButton3);
        jButton3.setBounds(110, 90, 100, 22);

        jButton4.setText("Kitap Onay");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        add(jButton4);
        jButton4.setBounds(210, 90, 100, 22);

        btnCikis.setText("Çıkış");
        add(btnCikis);
        btnCikis.setBounds(510, 50, 100, 22);

        jButton6.setText("Yetkili Ekle");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        add(jButton6);
        jButton6.setBounds(420, 90, 100, 22);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(139, 69, 0));
        jLabel2.setText("Yetki : ");
        add(jLabel2);
        jLabel2.setBounds(90, 380, 150, 22);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(139, 69, 0));
        jLabel3.setText("Adınız : ");
        add(jLabel3);
        jLabel3.setBounds(90, 150, 150, 22);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(139, 69, 0));
        jLabel4.setText("Soyadınız : ");
        add(jLabel4);
        jLabel4.setBounds(90, 190, 150, 22);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(139, 69, 0));
        jLabel5.setText("Kullanıcı Adı : ");
        add(jLabel5);
        jLabel5.setBounds(90, 230, 150, 22);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(139, 69, 0));
        jLabel6.setText("Şifreniz : ");
        add(jLabel6);
        jLabel6.setBounds(90, 280, 150, 22);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(139, 69, 0));
        jLabel7.setText("Şifre Tekrar : ");
        add(jLabel7);
        jLabel7.setBounds(90, 330, 150, 22);
        add(boxAd);
        boxAd.setBounds(320, 150, 150, 22);
        add(boxSoyad);
        boxSoyad.setBounds(320, 190, 150, 22);

        boxKad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxKadActionPerformed(evt);
            }
        });
        add(boxKad);
        boxKad.setBounds(320, 230, 150, 22);

        comboYetki.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "admin", "Öğrenci", "Öğretmen" }));
        comboYetki.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboYetkiActionPerformed(evt);
            }
        });
        add(comboYetki);
        comboYetki.setBounds(320, 370, 80, 20);

        btnYetki.setText("Yetki Ver");
        btnYetki.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnYetkiActionPerformed(evt);
            }
        });
        add(btnYetki);
        btnYetki.setBounds(320, 410, 100, 23);
        add(boxSifre2);
        boxSifre2.setBounds(320, 320, 150, 22);
        add(boxSifre);
        boxSifre.setBounds(320, 280, 150, 22);
    }// </editor-fold>//GEN-END:initComponents

    private void boxKadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxKadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boxKadActionPerformed

    private void comboYetkiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboYetkiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboYetkiActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        //yetkili
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        AdminUyeIslem aui = new AdminUyeIslem(frame);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        AdminKitapIslem aki = new AdminKitapIslem(frame);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        AdminKitapOnay ako = new AdminKitapOnay(frame);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        AdminDuyuruEkle ade = new AdminDuyuruEkle(frame, "");
    }//GEN-LAST:event_jButton1ActionPerformed

    private int getId() {
        int x = 0;
        try {
            Statement stmt = con.createStatement();
            ResultSet rs = stmt.executeQuery("Select max(id) from Kullanici");
            rs.next();
            x = rs.getInt(1);
        } catch (SQLException ex) {
            //System.out.println("ID hatası oluştu");
        }
        return x;
    }

    private boolean isNickTaken(String nick) {
        try {
            Statement stmt = con.createStatement();
            ResultSet rs = stmt.executeQuery("SELECT kullaniciAdi from Kullanici "
                    + " where kullaniciAdi='" + nick + "'");
            rs.next();
            rs.getString(1);
            return false;
        } catch (SQLException ex) {
            //System.out.println("ID Hata olustu");
            return true;
        }
    }
    private void btnYetkiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnYetkiActionPerformed
        if (!boxAd.getText().equals("") && !boxSoyad.getText().equals("")
                && !boxKad.getText().equals("") && !boxSifre.getText().equals("")
                && !boxSifre2.getText().equals("")) {
            if (boxSifre.getText().equals(boxSifre2.getText())) {
                if (isNickTaken(boxKad.getText())) {
                    String sorgu = "INSERT INTO Kullanici (id,ad,soyad,kullaniciAdi,sifre,yetki) "
                            + " VALUES ('" + (getId() + 1) + "','" + boxAd.getText() + "','" + boxSoyad.getText()
                            + "','" + boxKad.getText() + "','" + boxSifre.getText() + "','" + comboYetki.getSelectedItem() + "')";
                    Ekle e = new Ekle(con, sorgu);
                    JOptionPane.showMessageDialog(this, "Başarıyla Eklendi");
                    boxAd.setText("");
                    boxSoyad.setText("");
                    boxKad.setText("");
                    boxSifre.setText("");
                    boxSifre2.setText("");
                    comboYetki.setSelectedIndex(0);
                } else {
                    JOptionPane.showMessageDialog(this, "Farklı Kullanici Adı Deneyin!");
                }
            } else {
                JOptionPane.showMessageDialog(this, "Şifreler Uyusmuyor");
            }

        } else {
            JOptionPane.showMessageDialog(this, "Bütün Alanları Doldurun");
        }

    }//GEN-LAST:event_btnYetkiActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField boxAd;
    private javax.swing.JTextField boxKad;
    private javax.swing.JPasswordField boxSifre;
    private javax.swing.JPasswordField boxSifre2;
    private javax.swing.JTextField boxSoyad;
    private javax.swing.JButton btnCikis;
    private javax.swing.JButton btnYetki;
    private javax.swing.JComboBox<String> comboYetki;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables
}
