package yuksi.GUI.AdminIslemleri;

import yuksi.Giris;
import VeriErisimSiniflari.Baglan;
import VeriErisimSiniflari.Ekle;
import VeriErisimSiniflari.Guncelle;
import static VeriErisimSiniflari.SQL_Server_Connection.con;
import VeriErisimSiniflari.Sil;
import VeriErisimSiniflari.VerileriGoster;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class AdminKitapIslem extends javax.swing.JPanel {

    JFrame frame;
    Connection con;
    VerileriGoster vg;
    DefaultTableModel modelTable;
    boolean guncelle = false;
    Baglan b;

    public AdminKitapIslem(JFrame frame) {
        initComponents();

        this.frame = frame;
        frame.setContentPane(this);
        frame.setSize(900, 560);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.setVisible(true);
        try {
            con = DriverManager.getConnection("jdbc:sqlserver://127.0.0.1:1433;database=Kutuphane;user=root;password=1234");
        } catch (SQLException ex) {
            System.out.println("Bağlantı Hatası");
        }
        String sorgu = "SELECT kitapId,kitapAd,kitapTur,yazar,yayinEvi,yerNo FROM Kitaplik";
        vg = new VerileriGoster(con, sorgu);
        modelTable = vg.getTable((DefaultTableModel) jTable1.getModel());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        btnCikis = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        kitapTur = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        yerNo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnEkle = new javax.swing.JButton();
        btnSil = new javax.swing.JButton();
        kitapAd = new javax.swing.JTextField();
        yazar = new javax.swing.JTextField();
        yayinEvi = new javax.swing.JTextField();
        btnDuzenle = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        boxAra = new javax.swing.JTextField();
        btnAra = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setLayout(null);

        jButton1.setText("Duyuru Ekle");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1);
        jButton1.setBounds(310, 50, 110, 22);

        jButton2.setText("Üye İşlem");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2);
        jButton2.setBounds(10, 50, 100, 22);

        jButton3.setText("Kitap İşlem");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        add(jButton3);
        jButton3.setBounds(110, 50, 100, 22);

        jButton4.setText("Kitap Onay");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        add(jButton4);
        jButton4.setBounds(210, 50, 100, 22);

        jButton5.setText("Yetkili Ekle");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        add(jButton5);
        jButton5.setBounds(420, 50, 100, 22);

        btnCikis.setText("Çıkış");
        btnCikis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCikisActionPerformed(evt);
            }
        });
        add(btnCikis);
        btnCikis.setBounds(730, 20, 100, 23);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        kitapTur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kitapTurActionPerformed(evt);
            }
        });
        jPanel1.add(kitapTur);
        kitapTur.setBounds(150, 50, 660, 22);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(139, 69, 0));
        jLabel3.setText("Kitap Adı");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(10, 20, 100, 22);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(139, 69, 0));
        jLabel4.setText("Kitap Türü");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(10, 50, 100, 22);

        yerNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yerNoActionPerformed(evt);
            }
        });
        jPanel1.add(yerNo);
        yerNo.setBounds(150, 160, 290, 22);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(139, 69, 0));
        jLabel5.setText("Yazar");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(10, 90, 100, 22);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(139, 69, 0));
        jLabel6.setText("Yer Numarası");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(10, 160, 100, 22);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(139, 69, 0));
        jLabel7.setText("Yayın Evi");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(10, 120, 100, 22);

        btnEkle.setText("Ekle");
        btnEkle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEkleActionPerformed(evt);
            }
        });
        jPanel1.add(btnEkle);
        btnEkle.setBounds(490, 160, 80, 30);

        btnSil.setText("Sil");
        btnSil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSilActionPerformed(evt);
            }
        });
        jPanel1.add(btnSil);
        btnSil.setBounds(690, 160, 80, 30);
        jPanel1.add(kitapAd);
        kitapAd.setBounds(150, 20, 660, 22);
        jPanel1.add(yazar);
        yazar.setBounds(150, 90, 660, 22);
        jPanel1.add(yayinEvi);
        yayinEvi.setBounds(150, 120, 660, 22);

        btnDuzenle.setText("Düzenle");
        btnDuzenle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDuzenleActionPerformed(evt);
            }
        });
        jPanel1.add(btnDuzenle);
        btnDuzenle.setBounds(590, 160, 80, 30);

        add(jPanel1);
        jPanel1.setBounds(20, 80, 820, 200);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(null);

        boxAra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxAraActionPerformed(evt);
            }
        });
        jPanel2.add(boxAra);
        boxAra.setBounds(220, 20, 200, 25);

        btnAra.setText("ARA");
        btnAra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAraActionPerformed(evt);
            }
        });
        jPanel2.add(btnAra);
        btnAra.setBounds(450, 20, 70, 23);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Kitap Adı", "Kitap Türü", "Yazar", "Yayın Evi", "Yer Numarası"
            }
        ));
        jTable1.setToolTipText("");
        jScrollPane1.setViewportView(jTable1);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(20, 60, 800, 170);

        add(jPanel2);
        jPanel2.setBounds(20, 290, 820, 250);
    }// </editor-fold>//GEN-END:initComponents

    private void kitapTurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kitapTurActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kitapTurActionPerformed

    private void yerNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yerNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yerNoActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        AdminUyeIslem aui = new AdminUyeIslem(frame);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        AdminKitapIslem aki = new AdminKitapIslem(frame);

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        AdminKitapOnay ako = new AdminKitapOnay(frame);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        AdminDuyuruEkle ade = new AdminDuyuruEkle(frame, "");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        AdminYetkiliEkle aye = new AdminYetkiliEkle(frame);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void btnAraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAraActionPerformed

        String sorgu = "SELECT (kitapId,kitapAd,kitapTur,yazar,yayinEvi,yerNo) FROM Kitaplik "
                + "WHERE kitapAd='" + boxAra.getText() + "'";
        int konum = getArananRow(boxAra.getText());
        jTable1.setRowSelectionInterval(konum, konum);
        jTable1.scrollRectToVisible(jTable1.getCellRect(konum, 0, true));

    }//GEN-LAST:event_btnAraActionPerformed
    private int getArananRow(String aranan) {
        for (int i = 0; i < jTable1.getRowCount(); i++) {
            if (jTable1.getModel().getValueAt(i, 1).equals(aranan)) {
                return i;
            }
        }
        return 0;
    }
    private void boxAraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxAraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boxAraActionPerformed
    private int getKitapId() {
        int x = 0;
        try {
            Statement stmt = con.createStatement();
            ResultSet rs = stmt.executeQuery("Select max(kitapId) from Kitaplik");
            rs.next();
            x = rs.getInt(1);
        } catch (SQLException ex) {
            System.out.println("Listelerken hata oluştu");
        }
        return x;
    }

    private void btnEkleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEkleActionPerformed
        if (guncelle == true) {
            if (!kitapAd.getText().equals("") && !kitapTur.getText().equals("") && !yazar.getText().equals("")
                    && !yayinEvi.getText().equals("") && !yerNo.equals("")) {
                String sorgu = "update Kitaplik set kitapAd='" + kitapAd.getText()
                        + "' ,kitapTur='" + kitapTur.getText() + "' ,yazar='" + yazar.getText() + "',"
                        + " yayinEvi='" + yayinEvi.getText() + "', yerNo='" + yerNo.getText() + "'"
                        + " where kitapId=" + modelTable.getValueAt(jTable1.getSelectedRow(), 0);
                Guncelle g = new Guncelle(con, sorgu);
                for (int i = modelTable.getRowCount() - 1; i >= 0; i--) {
                    modelTable.removeRow(i);
                }

                modelTable = vg.getTable((DefaultTableModel) jTable1.getModel());
                kitapAd.setText("");
                kitapTur.setText("");
                yazar.setText("");
                yayinEvi.setText("");
                yerNo.setText("");
                guncelle = false;
            } else {
                JOptionPane.showMessageDialog(this, "Bütün Alanları Doldurun");
            }
        } else {
            if (!kitapAd.getText().equals("") && !kitapTur.getText().equals("") && !yazar.getText().equals("")
                    && !yayinEvi.getText().equals("") && !yerNo.equals("")) {
                String sorgu = "INSERT INTO Kitaplik (kitapId,kitapAd,kitapTur,yazar,yayinEvi,yerNo)"
                        + " VALUES ('" + (getKitapId() + 1) + "','" + kitapAd.getText() + "','" + kitapTur.getText()
                        + "','" + yazar.getText() + "','" + yayinEvi.getText() + "','" + yerNo.getText() + "')";
                Ekle e = new Ekle(con, sorgu);
                for (int i = modelTable.getRowCount() - 1; i >= 0; i--) {
                    modelTable.removeRow(i);
                }
                modelTable = vg.getTable((DefaultTableModel) jTable1.getModel());
                kitapAd.setText("");
                kitapTur.setText("");
                yazar.setText("");
                yayinEvi.setText("");
                yerNo.setText("");
            } else {
                JOptionPane.showMessageDialog(this, "Bütün Alanları Doldurun");
            }
        }

    }//GEN-LAST:event_btnEkleActionPerformed

    Sil sil;
    private void btnSilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSilActionPerformed
        String sorgu = "DELETE  Kitaplik WHERE kitapId='"
                + modelTable.getValueAt(jTable1.getSelectedRow(), 0) + "'";
        sil = new Sil(con, sorgu);
        for (int i = modelTable.getRowCount() - 1; i >= 0; i--) {
            modelTable.removeRow(i);
        }
        modelTable = vg.getTable((DefaultTableModel) jTable1.getModel());
    }//GEN-LAST:event_btnSilActionPerformed

    private void btnCikisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCikisActionPerformed
        Giris GE = new Giris(frame);
    }//GEN-LAST:event_btnCikisActionPerformed

    private void btnDuzenleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDuzenleActionPerformed
        if (jTable1.getSelectedRow() != -1) {
            guncelle = !guncelle;
            if (guncelle == true) {
                JOptionPane.showMessageDialog(this, "Guncelleme yapılıyor.");
                try {
                    Statement stmt = con.createStatement();
                    ResultSet rs = stmt.executeQuery("Select kitapAd,kitapTur,yazar,yayinEvi,yerNo from Kitaplik "
                            + " where kitapId=" + modelTable.getValueAt(jTable1.getSelectedRow(), 0));
                    rs.next();
                    kitapAd.setText(rs.getString(1));
                    kitapTur.setText(rs.getString(2));
                    yazar.setText(rs.getString(3));
                    yayinEvi.setText(rs.getString(4));
                    yerNo.setText(rs.getString(5));

                } catch (SQLException ex) {
                    System.out.println("Kitap bilgilerini alırken hata oluştu");
                }
            } else {
                kitapAd.setText("");
                kitapTur.setText("");
                yazar.setText("");
                yayinEvi.setText("");
                yerNo.setText("");
                JOptionPane.showMessageDialog(this, "Guncelleme islemi iptal edildi.");
            }

        }


    }//GEN-LAST:event_btnDuzenleActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField boxAra;
    private javax.swing.JButton btnAra;
    private javax.swing.JButton btnCikis;
    private javax.swing.JButton btnDuzenle;
    private javax.swing.JButton btnEkle;
    private javax.swing.JButton btnSil;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField kitapAd;
    private javax.swing.JTextField kitapTur;
    private javax.swing.JTextField yayinEvi;
    private javax.swing.JTextField yazar;
    private javax.swing.JTextField yerNo;
    // End of variables declaration//GEN-END:variables
}
