package yuksi.GUI.AdminIslemleri;

import yuksi.Giris;
import VeriErisimSiniflari.Baglan;
import VeriErisimSiniflari.Guncelle;
import static VeriErisimSiniflari.SQL_Server_Connection.con;
import VeriErisimSiniflari.VerileriGoster;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class AdminKitapOnay extends javax.swing.JPanel {

    Baglan b;
    JFrame frame;
    DefaultTableModel modelTable;
    VerileriGoster vg;

    public AdminKitapOnay(JFrame frame) {
        initComponents();

        this.frame = frame;
        frame.setContentPane(this);
        frame.setSize(900, 560);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.setVisible(true);
        try {
            con = DriverManager.getConnection("jdbc:sqlserver://127.0.0.1:1433;database=Kutuphane;user=root;password=1234");
        } catch (SQLException ex) {
            System.out.println("Bağlantı Hatası");
        }

        String sorgu = "SELECT ad,id,kitapId,kitapAd,kitapOnay FROM "
                + "Kitaplik ki , Kullanici ku where "
                + "ku.id=ki.kitapIstekId and ki.kitapOnay='İstendi'";
        vg = new VerileriGoster(con, sorgu);
        modelTable = vg.getTable((DefaultTableModel) jTable1.getModel());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        btnCikis = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        checkOnay = new javax.swing.JCheckBox();
        btnOnay = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setLayout(null);

        jButton1.setText("Duyuru Ekle");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1);
        jButton1.setBounds(320, 110, 110, 22);

        jButton2.setText("Üye İşlem");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2);
        jButton2.setBounds(20, 110, 100, 22);

        jButton3.setText("Kitap İşlem");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        add(jButton3);
        jButton3.setBounds(120, 110, 100, 22);

        jButton4.setText("Kitap Onay");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        add(jButton4);
        jButton4.setBounds(220, 110, 100, 22);

        jButton5.setText("Yetkili Ekle");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        add(jButton5);
        jButton5.setBounds(430, 110, 100, 22);

        btnCikis.setText("Çıkış");
        btnCikis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCikisActionPerformed(evt);
            }
        });
        add(btnCikis);
        btnCikis.setBounds(740, 60, 100, 23);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Üye Adı", "Üye Id", "Kitap Id", "Kitap Adı", "Kitap Onay"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(20, 70, 800, 160);

        checkOnay.setText("Onay Ver");
        checkOnay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkOnayActionPerformed(evt);
            }
        });
        jPanel1.add(checkOnay);
        checkOnay.setBounds(200, 240, 81, 23);

        btnOnay.setText("ONAYLA");
        btnOnay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOnayActionPerformed(evt);
            }
        });
        jPanel1.add(btnOnay);
        btnOnay.setBounds(280, 320, 280, 60);

        jLabel1.setText("Jonay");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(170, 410, 120, 40);

        add(jPanel1);
        jPanel1.setBounds(60, 150, 830, 400);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        AdminUyeIslem aui = new AdminUyeIslem(frame);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        AdminKitapIslem aki = new AdminKitapIslem(frame);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        AdminKitapOnay ako = new AdminKitapOnay(frame);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        AdminDuyuruEkle ade = new AdminDuyuruEkle(frame, "");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        AdminYetkiliEkle aye = new AdminYetkiliEkle(frame);
    }//GEN-LAST:event_jButton5ActionPerformed
    private int getKitapCount(String id) {
        int x = 0;

        try {
            Statement stmt = con.createStatement();
            ResultSet rs = stmt.executeQuery("select kitapCount from Kullanici where id='"
                    + id + "'");
            rs.next();
            x = rs.getInt(1);
        } catch (SQLException ex) {
            System.out.println("Onay KCount hata oluştu");
        }
        System.out.println(x);
        return --x;
    }
    private void btnOnayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOnayActionPerformed
        if (jTable1.getSelectedRow() != -1) {
            String sorgu;
            if (checkOnay.isSelected()) {
                sorgu = "update Kitaplik set kitapOnay='Onaylandı' WHERE kitapId="
                        + modelTable.getValueAt(jTable1.getSelectedRow(), 2);
                sorgu += "update Kitaplik set kitapSahibiId="
                        + modelTable.getValueAt(jTable1.getSelectedRow(), 1) + " WHERE kitapId="
                        + modelTable.getValueAt(jTable1.getSelectedRow(), 2);

                sorgu += "update Kitaplik set alisTarihi=getdate() where kitapId="
                        + modelTable.getValueAt(jTable1.getSelectedRow(), 2);
                sorgu += "update Kitaplik set teslimTarihi=dateadd(month,1,alisTarihi) where kitapId="
                        + modelTable.getValueAt(jTable1.getSelectedRow(), 2);
                JOptionPane.showMessageDialog(this, "Başarıyla Onaylandı");
            } else {
                sorgu = "update Kitaplik set kitapOnay='Onaylanmadı' WHERE kitapId="
                        + modelTable.getValueAt(jTable1.getSelectedRow(), 2);
                sorgu += "update Kullanici set kitapCount="
                        + getKitapCount(modelTable.getValueAt(jTable1.getSelectedRow(), 1)
                                + " WHERE id="
                                + modelTable.getValueAt(jTable1.getSelectedRow(), 1));
                JOptionPane.showMessageDialog(this, "Kitap Onaylanmadı");
            }
            Guncelle g = new Guncelle(con, sorgu);
            for (int i = modelTable.getRowCount() - 1; i >= 0; i--) {
                modelTable.removeRow(i);
            }
            modelTable = vg.getTable((DefaultTableModel) jTable1.getModel());
        }

    }//GEN-LAST:event_btnOnayActionPerformed

    private void btnCikisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCikisActionPerformed
        Giris GE = new Giris(frame);
    }//GEN-LAST:event_btnCikisActionPerformed

    private void checkOnayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkOnayActionPerformed


    }//GEN-LAST:event_checkOnayActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCikis;
    private javax.swing.JButton btnOnay;
    private javax.swing.JCheckBox checkOnay;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
